language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libmysqlclient-dev libmysqld-dev libwrap0-dev
 - perlbrew install-cpanm -f
install:
  - cpanm --quiet DBI Test::Pod Test::Deep Test::DistManifest Proc::ProcessTable
script: "export RELEASE_TESTING=1 && perl Makefile.PL && make disttest && perl Makefile.PL --force-embedded && make disttest"
